# Generated by Django 4.2.5 on 2023-09-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='diatonic',
            field=models.CharField(choices=[('major', 'Major'), ('minor', 'Minor')], default='major', max_length=20),
        ),
        migrations.AddField(
            model_name='sheet',
            name='key',
            field=models.CharField(choices=[('cflat', 'C♭'), ('cnatural', 'C'), ('csharp', 'C♯'), ('dflat', 'D♭'), ('dnatural', 'D'), ('dsharp', 'D♯'), ('eflat', 'E♭'), ('enatural', 'E'), ('esharp', 'E♯'), ('fflat', 'F♭'), ('fnatural', 'F'), ('fsharp', 'F♯'), ('gflat', 'G♭'), ('gnatural', 'G'), ('gsharp', 'G♯'), ('aflat', 'A♭'), ('anatural', 'A'), ('asharp', 'A♯'), ('bflat', 'B♭'), ('bnatural', 'B')], default='cnatural', max_length=20),
        ),
    ]
