# Generated by Django 4.2.5 on 2023-09-13 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_sheet_diatonic_sheet_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Listening Date')),
                ('performer', models.CharField(max_length=100)),
                ('review', models.CharField(choices=[('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='1', max_length=5)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.sheet')),
            ],
        ),
    ]
