# Generated by Django 4.2.5 on 2023-09-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_listening'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('notes', models.TextField(max_length=250)),
                ('date', models.DateField(verbose_name='Day Practiced')),
            ],
        ),
        migrations.AlterModelOptions(
            name='listening',
            options={'ordering': ['-review']},
        ),
        migrations.AddField(
            model_name='sheet',
            name='practices',
            field=models.ManyToManyField(to='main_app.practice'),
        ),
    ]
